<?php

/**
 * AttendanceRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AttendanceRecord extends PluginAttendanceRecord
{
    /**
     * @ignore
     */
    private $attendanceService;

    /**
     * @ignore
     * @return type
     */
    public function getAttendanceService() {
        if(is_null($this->attendanceService)) {
            $this->attendanceService = new AttendanceService();
            $this->attendanceService->setAttendanceDao(new AttendanceDao());
        }
        return $this->attendanceService;
    }
    public function checkAttendanceMarkedAlready($employee_id, $punchInDate, $punchOutDate){
        $attendanceService = $this->getAttendanceService();
        $attendanceRecord = $attendanceService->getAttendanceState($employee_id, $punchInDate, $punchOutDate);
        return $attendanceRecord;
    }

}
