<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/11/15 16:54:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm_mysql',
  'username' => 'root',
  'password' => 'bCs032401113313@@',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
