<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/11/15 17:05:34
sfConfig::add(array(
  'mod_securityauthentication_enabled' => true,
  'mod_securityauthentication_view_class' => 'sfPHP',
));
