<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/06/18 11:47:11
sfConfig::add(array(
  'mod_securityauthentication_enabled' => true,
  'mod_securityauthentication_view_class' => 'sfPHP',
));
