<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/06/20 13:07:19
sfConfig::add(array(
  'mod_recruitmentapply_enabled' => true,
  'mod_recruitmentapply_view_class' => 'sfPHP',
));
